# Generated by Django 2.2.7 on 2019-11-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_alert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='sended',
            field=models.BooleanField(default=False),
        ),
    ]
