# Generated by Django 2.2.7 on 2019-11-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_alert', '0002_coin_sended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='value',
            field=models.FloatField(),
        ),
    ]
