# Generated by Django 2.2.7 on 2019-11-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_alert', '0003_auto_20191126_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='comparate',
            field=models.IntegerField(default=0),
        ),
    ]
